theme: minima
title: This is my title
author: parragiWeb
email: my-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 This my awesome description for my new site here. I edited this
  line in _config.yml. It appears in my document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
